### ISSUE TITLE
Theme for NeoVim

### ISSUE THREAD

**Issue by daltonmenezes** [daltonmenezes/aura-theme#132]
### Discussed in https://github.com/daltonmenezes/aura-theme/discussions/125

<div type='discussions-op-text'>

<sup>Originally posted by **marilira** September 18, 2021</sup>
I use the theme on vscode and would also to use on my Neovim :) </div>

### Status: in development by [baliestri](https://github.com/baliestri)

**Comment by baliestri** [comment]
Anyone interested in using it even **incomplete**: [neovim-port](https://github.com/baliestri/aura-theme/tree/feat/neovim-port/packages/neovim)

**Comment by rjorge99** [comment]
Hi, are there any news about the progress? thanks

**Comment by baliestri** [comment]
> Hi, are there any news about the progress? thanks

Well, I haven't made changes to it for 8 months, there are some things that should change, for example the color of the tabs, but it's very functional. Because it was incomplete, I decided not to commit it to the main repository from `daltonmenezes`

https://github.com/baliestri/aura-theme/tree/feat/neovim-port/packages/neovim
